/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei/native";
import { Asset } from "expo-asset";
import ExpoTHREE, { THREE } from "expo-three";
import React from "react";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Door: THREE.Mesh;
    Handle: THREE.Mesh;
    Lock: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
    Handle: THREE.MeshPhysicalMaterial;
    Lock: THREE.MeshStandardMaterial;
  };
};
type DoorProps = {
  textureUrl: any;
  roughnessMetalness: { r: number; m: number };
  hdrIntensity: number;
  textureRepeat?: [number, number];
  color?: string;
};

export function Door({
  textureUrl,
  roughnessMetalness,
  hdrIntensity,
  textureRepeat = [1, 1],
  color = "#ffffff",
}: DoorProps) {
  const modelAsset = Asset.fromModule(require("../assets/models/Door.glb")).uri;
  const { nodes, materials, scene } = useGLTF(
    modelAsset
  ) as unknown as GLTFResult;

  // const texture = useMemo(() => {
  //   const asset = Asset.fromModule(require("../assets/images/lami4.jpg"));
  //   let tex = new THREE.Texture();

  //   loadTextureAsync({ asset }).then((loaded) => {
  //     loaded.wrapS = loaded.wrapT = THREE.RepeatWrapping;
  //     loaded.repeat.set(textureRepeat[0], textureRepeat[1]);
  //     tex.copy(loaded);
  //     tex.needsUpdate = true;
  //   });

  //   return tex;
  // }, [textureUrl, textureRepeat]);
  function useTexture(
    asset: Asset | null,
    repeat: [number, number] = [1, 1]
  ): THREE.Texture | null {
    const [texture, setTexture] = React.useState<THREE.Texture | null>(null);

    React.useEffect(() => {
      if (!asset) {
        setTexture(null);
        return;
      }

      let cancelled = false;

      (async () => {
        try {
          await asset.downloadAsync(); // ensure it's loaded
          const tex = await ExpoTHREE.loadAsync(asset);

          if (cancelled) return;

          // tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
          tex.wrapS = tex.wrapT = THREE.ClampToEdgeWrapping;
          // tex.repeat.set(repeat[0], repeat[1]);
          tex.needsUpdate = true;

          setTexture(tex);
        } catch (e) {
          console.warn("Error loading texture:", e);
          setTexture(null);
        }
      })();

      return () => {
        cancelled = true;
      };
    }, [asset, repeat]);

    return texture;
  }

  const texture = useTexture(textureUrl, textureRepeat);

  React.useEffect(() => {
    if (!texture) return;
    scene.traverse((child) => {
      if (child instanceof THREE.Mesh && child.name === "Door") {
        const mat = new THREE.MeshStandardMaterial({
          map: texture,
          color: new THREE.Color(color || "#ffffff"),
          roughness: roughnessMetalness.r,
          metalness: roughnessMetalness.m,
        });
        child.material = mat;
        child.material.needsUpdate = true;
      }
    });
  }, [scene, texture, color, roughnessMetalness]);

  return (
    <group scale={[0.5, 0.5, 0.5]} dispose={null}>
      <primitive object={scene} />
    </group>
  );
}
