// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import { useGLTF } from "@react-three/drei/native";
// import { useLoader } from "@react-three/fiber";
// import { Asset } from "expo-asset";
// import ExpoTHREE, { TextureLoader, THREE } from "expo-three";
// import React from "react";
// import { GLTF } from "three-stdlib";

// type GLTFResult = GLTF & {
//   nodes: {
//     Door: THREE.Mesh;
//     Handle: THREE.Mesh;
//     Lock: THREE.Mesh;
//   };
//   materials: {
//     ["Material.001"]: THREE.MeshStandardMaterial;
//     Handle: THREE.MeshPhysicalMaterial;
//     Lock: THREE.MeshStandardMaterial;
//   };
// };
// type DoorProps = {
//   textureUrl: string | Asset | null;
//   roughnessMetalness: { r: number; m: number };
//   hdrIntensity: number;
//   textureRepeat?: [number, number];
//   color?: string;
// };

// export function Door({
//   textureUrl,
//   roughnessMetalness,
//   hdrIntensity,
//   textureRepeat = [1, 1],
//   color = "#ffffff",
// }: DoorProps) {
//   const modelAsset = Asset.fromModule(require("../assets/models/Door.glb")).uri;
//   const { nodes, materials, scene } = useGLTF(
//     modelAsset
//   ) as unknown as GLTFResult;

//   // const texture = useMemo(() => {
//   //   const asset = Asset.fromModule(require("../assets/images/lami4.jpg"));
//   //   let tex = new THREE.Texture();

//   //   loadTextureAsync({ asset }).then((loaded) => {
//   //     loaded.wrapS = loaded.wrapT = THREE.RepeatWrapping;
//   //     loaded.repeat.set(textureRepeat[0], textureRepeat[1]);
//   //     tex.copy(loaded);
//   //     tex.needsUpdate = true;
//   //   });

//   //   return tex;
//   // }, [textureUrl, textureRepeat]);
//   function useTexture(asset: Asset | null, repeat: [number, number] = [1, 1]) {
//     const [texture, setTexture] = React.useState<THREE.Texture | null>(null);

//     React.useEffect(() => {
//       if (!asset) {
//         setTexture(null);
//         return;
//       }

//       let cancelled = false;

//       (async () => {
//         try {
//           await asset.downloadAsync(); // Load the asset first
//           const tex = await ExpoTHREE.loadAsync(asset);

//           if (cancelled) return;

//           tex.wrapS = THREE.RepeatWrapping;
//           tex.wrapT = THREE.RepeatWrapping;
//           tex.repeat.set(repeat[0], repeat[1]);
//           tex.needsUpdate = true;

//           setTexture(tex);
//         } catch (e) {
//           console.warn("Error loading texture:", e);
//           setTexture(null);
//         }
//       })();

//       return () => {
//         cancelled = true;
//       };
//     }, [asset, repeat]);

//     return texture;
//   }

//   const texture = useLoader(
//     TextureLoader,
//     typeof textureUrl === "string" ? textureUrl : textureUrl?.uri ?? ""
//   );

//   React.useEffect(() => {
//     if (!texture) return;

//     texture.wrapS = THREE.RepeatWrapping;
//     texture.wrapT = THREE.RepeatWrapping;
//     texture.minFilter = THREE.LinearMipMapLinearFilter;
//     texture.magFilter = THREE.LinearFilter;
//     texture.needsUpdate = true;

//     scene.traverse((child) => {
//       if (child instanceof THREE.Mesh && child.name === "Door") {
//         child.material.map = texture;
//         child.material.needsUpdate = true;
//       }
//     });
//   }, [scene, texture]);

//   return (
//     <group scale={[0.5, 0.5, 0.5]} dispose={null}>
//       <primitive object={scene} />
//     </group>
//   );
// }
import { useGLTF } from "@react-three/drei/native";
import { useLoader } from "@react-three/fiber";
import { Asset } from "expo-asset";
import { TextureLoader, THREE } from "expo-three";
import React, { useEffect } from "react";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Door: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

type DoorProps = {
  textureUrl: string | Asset | null;
  roughnessMetalness: { r: number; m: number };
  hdrIntensity: number;
  textureRepeat?: [number, number];
  color?: string;
};

export function Door({
  textureUrl,
  roughnessMetalness,
  hdrIntensity,
  textureRepeat = [1, 1],
  color = "#ffffff",
}: DoorProps) {
  const modelAsset = Asset.fromModule(require("../assets/models/Door.glb")).uri;
  const { nodes, materials, scene } = useGLTF(
    modelAsset
  ) as unknown as GLTFResult;

  const texture = useLoader(
    TextureLoader,
    typeof textureUrl === "string" ? textureUrl : textureUrl?.uri ?? ""
  );

  useEffect(() => {
    if (!texture) return;

    texture.wrapS = THREE.RepeatWrapping;
    texture.wrapT = THREE.RepeatWrapping;
    texture.minFilter = THREE.LinearMipMapLinearFilter;
    texture.magFilter = THREE.LinearFilter;
    texture.needsUpdate = true;

    scene.traverse((child) => {
      if (child instanceof THREE.Mesh && child.name === "Door") {
        child.material = new THREE.MeshStandardMaterial({
          map: texture,
          color: new THREE.Color(color || "#ffffff"),
          roughness: roughnessMetalness.r,
          metalness: roughnessMetalness.m,
        });
        child.material.needsUpdate = true;
      }
    });
  }, [scene, texture, color, roughnessMetalness]);

  return (
    <group scale={[0.5, 0.5, 0.5]} dispose={null}>
      <primitive object={scene} />
    </group>
  );
}
