/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useGLTF } from "@react-three/drei/native";
import { Asset } from "expo-asset";
import React, { JSX, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["01_objects002"]: THREE.Mesh;
    COMPOUND001: THREE.Mesh;
    COMPOUND001001: THREE.Mesh;
    COMPOUND002001: THREE.Mesh;
  };
  materials: {
    mat_0: THREE.MeshStandardMaterial;
    ["mat_0.001"]: THREE.MeshStandardMaterial;
    mat_1: THREE.MeshStandardMaterial;
  };
};

type ActionName = "COMPOUND.001Action";

export function Starlink(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const modelAsset = Asset.fromModule(
    require("../assets/models/Starlink.glb")
  ).uri;
  const { nodes, materials, animations } = useGLTF(
    modelAsset
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="01_objects002"
          castShadow
          receiveShadow
          geometry={nodes["01_objects002"].geometry}
          material={materials.mat_0}
          position={[0, 1.407, 0]}
          rotation={[0, -1.566, 0]}
          scale={4.23}
        />
        <group
          name="01_objects"
          position={[0, 1.687, 0]}
          rotation={[0, -1.566, 0]}
          scale={4.23}
        >
          <group name="COMPOUND003001">
            <mesh
              name="COMPOUND001"
              castShadow
              receiveShadow
              geometry={nodes.COMPOUND001.geometry}
              material={materials["mat_0.001"]}
              position={[0.004, -0.029, -0.015]}
            />
            <mesh
              name="COMPOUND001001"
              castShadow
              receiveShadow
              geometry={nodes.COMPOUND001001.geometry}
              material={materials.mat_1}
            />
            <mesh
              name="COMPOUND002001"
              castShadow
              receiveShadow
              geometry={nodes.COMPOUND002001.geometry}
              material={materials.mat_1}
            />
          </group>
        </group>
      </group>
    </group>
  );
}
